name: Deploy ryanjyoder.com/tech-hubs-africa

on: 
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo snap install hugo --channel=extended
        sudo apt install lftp
    - name: build site
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        export PATH=$PATH:/snap/bin
        export OUTPUT_DIR='pulbic'
        export LFTP_PASSWORD=$FTP_PASSWORD
        export REMOTE_PATH='/tech-hubs-africa'

        # get theme (submodule)
        git submodule update --init

        # generate html
        hugo -d $OUTPUT_DIR -D

        # upload static html
        lftp --env-password -u $FTP_USER $FTP_HOST -e "set ftp:ssl-allow no; mirror -R $OUTPUT_DIR $REMOTE_PATH; quit"
